apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-data-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  nfs:
    path: {{ .Values.nfs.paths.data }}
    server: {{ .Values.nfs.server }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-music-pv
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs
  nfs:
    path: {{ .Values.nfs.paths.music }}
    server: {{ .Values.nfs.server }}