---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: {{ .Values.name }}-data-pv
  storageClassName: nfs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-music-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: {{ .Values.name }}-music-pv
  storageClassName: nfs